#CREATING DATABASE
CREATE DATABASE ROYALINTERNATIONALSCHOOL;
USE ROYALINTERNATIONALSCHOOL;
#CREATE THE TABLES
CREATE TABLE STUDENT (
ROLL_NO INT auto_increment PRIMARY KEY,
STUDENT_NAME VARCHAR(50) NOT NULL,
MARKS INT default '0',
GRADE VARCHAR(2)
);

SELECT * FROM CLASSTEN;
#ADD COLUMN TO STUDENT TABLE
ALTER TABLE STUDENT ADD COLUMN CONTACT_NO INT;
#REMOVE GRADE COLUMN FROM STUDENT TABLE
ALTER TABLE STUDENT DROP COLUMN GRADE;
#RENAME THE STUDENT TABLE
RENAME TABLE STUDENT TO CLASSTEN;
#ADD VALUES TO THE TABLE
INSERT INTO CLASSTEN (STUDENT_NAME,MARKS)
VALUES
('ADAM ZAHIN','100'),
('ADHIL MUHAMMED','100'),
('AMEYA MARIA','100'),
('AYRA NIHA','100'),
('BILAL','90'),
('DUA','96');
#DELETE ALL ROWS CLASSTEN TABLE
TRUNCATE TABLE CLASSTEN;
#REMOVE TABLE FROM DATABASE
DROP TABLE CLASSTEN;

